from .api import MarkdownWord, render, render_string
from .batch import BatchResult, collect_markdown_inputs, render_many
from .config import (
    CacheConfig,
    CompilationLimits,
    FontConfig,
    FooterConfig,
    HeaderConfig,
    ImageConfig,
    Margins,
    ListConfig,
    MathFailurePolicy,
    MermaidConfig,
    ChartConfig,
    DataConfig,
    PageConfig,
    PerformanceConfig,
    PluginConfig,
    RenderConfig,
    ReproducibilityConfig,
    ResourcePolicy,
    TableConfig,
    TOCConfig,
    ValidationConfig,
    ReferenceConfig,
    NotesConfig,
    CitationConfig,
    AccessibilityConfig,
    FigureConfig,
    HeadingNumberingConfig,
    TitlePageConfig,
    AbstractConfig,
    CodeConfig,
    CalloutConfig,
    CommentConfig,
    FieldConfig,
    MetadataConfig,
    StyleMapConfig,
)
from .extensions import (
    AstTransformExtension,
    LayoutTransformExtension,
    MddocxExtension,
    load_entrypoint_extensions,
)
from .profiling import RenderStats
from .validation import validate_docx_package
from .inspection import DocxInspection, inspect_docx, inspect_docx_bytes
from .visual_qa import VisualQAReport, compare_visual_pages, render_docx_pages
from .accessibility import (
    AccessibilityFinding,
    AccessibilityReport,
    audit_docx_accessibility,
    audit_docx_accessibility_bytes,
)
from .benchmark import BenchmarkReport, run_performance_gate
from .api_stability import PUBLIC_API_VERSION, get_public_api_manifest
from .metadata import MetadataSanitizationReport, SanitizedMarkdown, sanitize_markdown_metadata
from .math.preflight import EquationCheck, MathPreflightReport, inspect_math, inspect_math_file
from .compiler import CompilationResult, Compiler, DocumentStageResult, LayoutStageResult
from .config_validation import validate_render_config
from .layout import (
    LAYOUT_SCHEMA_VERSION,
    BlockLayoutDecision,
    LayoutPlan,
    LayoutPlanner,
    TableLayoutDecision,
    TableWidthAllocation,
    allocate_table_widths_mm,
)
from .normalize import SemanticIndex, build_semantic_index
from .source import SourceDocument, acquire_markdown_source
from .project import (
    ProjectManifest,
    ProjectCompilation,
    ProjectBuildResult,
    ProjectWatchEvent,
    load_project,
    compile_project,
    build_project,
    watch_project,
    init_project,
    project_info,
)

__all__ = [
    "MarkdownWord",
    "RenderConfig",
    "Margins",
    "ListConfig",
    "PageConfig",
    "ResourcePolicy",
    "MathFailurePolicy",
    "MermaidConfig",
    "ChartConfig",
    "DataConfig",
    "HeaderConfig",
    "FooterConfig",
    "TOCConfig",
    "TableConfig",
    "FontConfig",
    "ImageConfig",
    "PerformanceConfig",
    "CompilationLimits",
    "ReproducibilityConfig",
    "ValidationConfig",
    "CacheConfig",
    "PluginConfig",
    "ReferenceConfig",
    "NotesConfig",
    "CitationConfig",
    "AccessibilityConfig",
    "FigureConfig",
    "HeadingNumberingConfig",
    "TitlePageConfig",
    "AbstractConfig",
    "CodeConfig",
    "CalloutConfig",
    "CommentConfig",
    "FieldConfig",
    "MetadataConfig",
    "StyleMapConfig",
    "MetadataSanitizationReport",
    "SanitizedMarkdown",
    "sanitize_markdown_metadata",
    "EquationCheck",
    "MathPreflightReport",
    "inspect_math",
    "inspect_math_file",
    "CompilationResult",
    "Compiler",
    "DocumentStageResult",
    "LayoutStageResult",
    "validate_render_config",
    "LayoutPlan",
    "LayoutPlanner",
    "TableLayoutDecision",
    "TableWidthAllocation",
    "allocate_table_widths_mm",
    "BlockLayoutDecision",
    "LAYOUT_SCHEMA_VERSION",
    "SemanticIndex",
    "build_semantic_index",
    "SourceDocument",
    "acquire_markdown_source",
    "RenderStats",
    "MddocxExtension",
    "AstTransformExtension",
    "LayoutTransformExtension",
    "load_entrypoint_extensions",
    "BatchResult",
    "collect_markdown_inputs",
    "render_many",
    "validate_docx_package",
    "DocxInspection",
    "inspect_docx",
    "inspect_docx_bytes",
    "VisualQAReport",
    "compare_visual_pages",
    "render_docx_pages",
    "render",
    "render_string",
    "ProjectManifest",
    "ProjectCompilation",
    "ProjectBuildResult",
    "ProjectWatchEvent",
    "load_project",
    "compile_project",
    "build_project",
    "watch_project",
    "init_project",
    "project_info",
    "AccessibilityFinding",
    "AccessibilityReport",
    "audit_docx_accessibility",
    "audit_docx_accessibility_bytes",
    "BenchmarkReport",
    "run_performance_gate",
    "PUBLIC_API_VERSION",
    "get_public_api_manifest",
]
__version__ = "1.2.3"
